export { default as setting } from './setting.svg'
export { default as logoWithText } from './logo-with-text.svg'
export { default as back } from './back.svg'
export { default as calendar } from './calendar.svg'
export { default as filterBlack } from './filter-black.svg'
export { default as filterCoral } from './filter-coral.svg'
